### ISSUE TITLE
npx fauna-schema-migrate hangs on some environments

### ISSUE THREAD

**Issue by botond-veress** [fauna-brecht/fauna-schema-migrate#2] opened 2021-02-12 18:19 UTC
If I run `npx fauna-schema-migrate init` it just hangs and loads indefinitely:
```bash
npx fauna-schema-migrate init
fetchMetadata: sill resolveWithNewModule fauna-schema-migrate@0.1.3-beta checking installable status
```

Installing it with `yarn` and running it, works as expected. It affects all versions published so far.

**Comment by fauna-brecht** [comment] 2021-02-22 14:42
Hey @botond-veress, what environment are you running on?
This seems like a problem installing the library and npm hanging to retrieve the version?

I tried it out a few times and it does seem to work here locally.
![image](https://user-images.githubusercontent.com/56540741/108723412-8379c480-7524-11eb-8a25-d16d954fe38c.png)

**Comment by botond-veress** [comment] 2021-02-22 14:56
Hey @fauna-brecht, OSX Catalina 10.15.7.
```
% node -v
v12.19.1
% npm -v
6.14.8
% npx -v
6.14.8
```
I don't have issues running any other package with `npx`. So weird.

**Comment by fauna-brecht** [comment] 2021-02-22 16:54
Strange indeed, very similar setup here. Can't really do anything though without reproducing it.

**Comment by TriangularCube** [comment] 2021-03-26 06:23
It's hanging pretty reliably on Github Actions in [my repo](https://github.com/mistfire-forge/hex/runs/2199549256)

**Comment by fauna-brecht** [comment] 2021-03-26 12:21
Probably not. 
"  ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported
"

Try with the --legacy option if you run it in your CI.

**Comment by TriangularCube** [comment] 2021-03-27 21:36
> Try with the --legacy option if you run it in your CI.

Yup that did it. Sorry for polluting the issue 😓

**Comment by fauna-brecht** [comment] 2021-04-21 13:01
I'll close it for now since I don't know whether it still happens and can't reproduce it.

**Closed by fauna-brecht** 2021-04-21 13:01 UTC
Labels: bug, help wanted
