### ISSUE TITLE
Function Body Change on Apply

### ISSUE THREAD

**Issue by michaelmerrill** [fauna-brecht/fauna-schema-migrate#1] opened 2021-02-11 22:45 UTC
Thank you so much for this tool. I realize it's in beta, but I wanted to get an early start and try it out.

For some reason the functions are different in Fauna than they are locally.

[Here is the function to apply.](https://github.com/michaelmerrill/fauna-schema-migrate-example/blob/main/fauna/resources/functions/get_account.js)

Here is the function in the Fauna Console:

```bash
Query(
  Lambda(
    "email",
    Let(
      {
        var1: Ref(
          Index("accounts_by_email"),
          Indexes(),
          Indexes(),
          1613082689952000,
          true,
          true,
          "accounts_by_email",
          Collection("accounts"),
          [Field(["data", "email"])],
          true,
          1
        )
      },
      If(
        Exists(Match(Select(["ref"], Var("var1")), Var("email"))),
        Get(Match(Select(["ref"], Var("var1")), Var("email"))),
        false
      )
    )
  )
)
```

And here is the error when I try and call the function:

```bash
Error: [
  {
    "code": "internal server error",
    "description": "java.lang.RuntimeException: Failed to deserialize stored QueryV in scope ScopeID(290269939794707976). Unparsed: Unparsed(ScopeID(290269939794707976),QueryV(4,{ "lambda" : [ "email", "name" ], "expr" : { "let" : { "var0" : { "ref" : DocID(1025,C1), "class" : DocID(1,C1), "collection" : DocID(1,C1), "ts" : 1613081878479000, "history_days" : 30, "name" : "accounts" }, "var1" : { "ref" : DocID(32768,C7), "class" : DocID(7,C1), "collection" : DocID(7,C1), "ts" : 1613081878479000, "active" : true, "serialized" : true, "name" : "accounts_by_email", "source" : DocID(1025,C1), "terms" : [ { "field" : [ "data", "email" ] } ], "unique" : true, "partitions" : 1 } }, "in" : { "if" : { "exists" : { "match" : { "select" : [ "ref" ], "from" : { "var" : "var1" } }, "terms" : { "var" : "email" } } }, "then" : false, "else" : { "let" : { "account" : { "create" : { "select" : [ "ref" ], "from" : { "var" : "var0" } }, "params" : { "object" : { "data" : { "object" : { "email" : { "var" : "email" }, "name" : { "var" : "name" } } } } } } }, "in" : { "object" : { "id" : { "select" : [ "ref", "id" ], "from" : { "var" : "account" } }, "email" : { "select" : [ "data", "email" ], "from" : { "var" : "account" } }, "name" : { "select" : [ "data", "name" ], "from" : { "var" : "account" } } } } } } } })) Errors: List(InvalidFormExpr(List(ref, class, collection, ts, history_days, name),["expr","let","var0"]), InvalidFormExpr(List(ref, class, collection, ts, active, serialized, name, source, terms, unique, partitions),["expr","let","var1"]))
Please report to support@fauna.com."
  }
]
```

To reproduce, clone [this repo](https://github.com/michaelmerrill/fauna-schema-migrate-example). Setup a new database in Fuana and get admin key. Then run:

```bash
$ npm run fauna generate
```

```bash
$ npm run fauna apply
```

If I get some time, I will try to debug.

Thanks again for the package!

**Comment by brunosmm** [comment] 2021-02-12 13:13
Hi @michaelmerrill,

I found the same problem, @fauna-brecht already fix and should release soon it. :) 
He can explain better the problem and solution.

**Comment by fauna-brecht** [comment] 2021-02-12 13:14
Thank you for your feedback (both of you). I have in the meantime determined the cause. It has to do something with how variables are interpreted inside a UDF so it's probably not an issue with the tool itself. I'm currently trying to gather more information whether the interpretation of variables inside UDFs is intended to work this way or not. 

There is a temporary fix which I already pushed to git and npm which should make sure the UDFs work, they still introduce a variable but the UDF should be equivalent in functionality. If that's not the case, please let me know.

**Comment by brunosmm** [comment] 2021-02-14 21:02
@fauna-brecht I tested on version 0.1.3-beta and it's all working! Thanks!

**Comment by fauna-brecht** [comment] 2021-02-23 16:38
Closing since I can't do more in the tool itself besides of the implemented workaround.

**Closed** 2021-02-23 16:37 UTC
Labels: bug, good first issue
